const state = {
  displayedBreeds: {
    displayedBreeds: [
      {
        id: 1,
        name: 'Affenpinscher',
        weight: '3 - 6',
        image: 'https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg',
        temperament:
          'Stubborn, Curious, Playful, Adventurous, Active, Fun-loving',
      },
      {
        id: 2,
        name: 'Afghan Hound',
        weight: '23 - 27',
        image: 'https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg',
        temperament: 'Aloof, Clownish, Dignified, Independent, Happy',
      },
      {
        id: 3,
        name: 'African Hunting Dog',
        weight: '20 - 30',
        image: 'https://cdn2.thedogapi.com/images/rkiByec47.jpg',
        temperament: 'Wild, Hardworking, Dutiful',
      },
      {
        id: 4,
        name: 'Airedale Terrier',
        weight: '18 - 29',
        image: 'https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg',
        temperament:
          'Outgoing, Friendly, Alert, Confident, Intelligent, Courageous',
      },
      {
        id: 5,
        name: 'Akbash Dog',
        weight: '41 - 54',
        image: 'https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg',
        temperament: 'Loyal, Independent, Intelligent, Brave',
      },
      {
        id: 6,
        name: 'Akita',
        weight: '29 - 52',
        image: 'https://cdn2.thedogapi.com/images/BFRYBufpm.jpg',
        temperament:
          'Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous',
      },
      {
        id: 7,
        name: 'Alapaha Blue Blood Bulldog',
        weight: '25 - 41',
        image: 'https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg',
        temperament: 'Loving, Protective, Trainable, Dutiful, Responsible',
      },
      {
        id: 8,
        name: 'Alaskan Husky',
        weight: '17 - 23',
        image: 'https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg',
        temperament: 'Friendly, Energetic, Loyal, Gentle, Confident',
      },
      {
        id: 9,
        name: 'Alaskan Malamute',
        weight: '29 - 45',
        image: 'https://cdn2.thedogapi.com/images/dW5UucTIW.jpg',
        temperament:
          'Friendly, Affectionate, Devoted, Loyal, Dignified, Playful',
      },
    ],
    temperaments: [
      'Active',
      'Adaptable',
      'Adventurous',
      'Affectionate',
      'Aggressive',
      'Agile',
      'Alert',
      'Aloof',
      'Amiable',
      'Assertive',
      'Athletic',
      'Attentive',
      'Benevolent',
      'Boisterous',
      'Bold',
      'Bossy',
      'Brave',
      'Bright',
      'Bubbly',
      'Calm',
      'Cat-like',
      'Cautious',
      'Charming',
      'Cheerful',
      'Clever',
      'Clownish',
      'Companionable',
      'Composed',
      'Confident',
      'Cooperative',
      'Courageous',
      'Cunning',
      'Curious',
      'Determined',
      'Devoted',
      'Dignified',
      'Diligent',
      'Docile',
      'Dominant',
      'Dutiful',
      'Eager',
      'Easygoing',
      'Energetic',
      'Even Tempered',
      'Excitable',
      'Extroverted',
      'Faithful',
      'Familial',
      'Fast',
      'Fearless',
      'Feisty',
      'Fierce',
      'Friendly',
      'Fun-loving',
      'Gay',
      'Generous',
      'Gentle',
      'Good-natured',
      'Good-tempered',
      'Great-hearted',
      'Happy',
      'Hard-working',
      'Hardworking',
      'Hardy',
      'Independent',
      'Inquisitive',
      'Intelligent',
      'Joyful',
      'Keen',
      'Kind',
      'Lively',
      'Lovable',
      'Loving',
      'Loyal',
      'Merry',
      'Mischievous',
      'Obedient',
      'Opinionated',
      'Outgoing',
      'Patient',
      'People-Oriented',
      'Playful',
      'Powerful',
      'Protective',
      'Proud',
      'Quick',
      'Quiet',
      'Rational',
      'Receptive',
      'Refined',
      'Reliable',
      'Reserved',
      'Respectful',
      'Responsible',
      'Responsive',
      'Rugged',
      'Self-assured',
      'Self-confidence',
      'Self-important',
      'Sensitive',
      'Sociable',
      'Spirited',
      'Spunky',
      'Stable',
      'Steady',
      'Strong',
      'Strong Willed',
      'Stubborn',
      'Sturdy',
      'Suspicious',
      'Sweet-Tempered',
      'Tenacious',
      'Territorial',
      'Thoughtful',
      'Tolerant',
      'Trainable',
      'Trusting',
      'Trustworthy',
      'Unflappable',
      'Vigilant',
      'Vocal',
      'Watchful',
      'Wild',
      'Willful',
    ],
    orderOption: 0,
    originOption: 'All',
    temperamentOption: 'All',
    searchedName: '',
  },
  pageNumber: 1,
};

export default state;
